#!groovy


pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                checkout scm
                sh 'docker build . -t reversing-figlet'
            }
        }
        stage('Test') {
            steps {
                echo 'TODO - tests!'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
