#!groovy


pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'cd mysterious-fail-1/ && docker build . -t reversing-figlet'
            }
        }
        stage('Test') {
            steps {
                sh '''
                set -ex
                cd mysterious-fail-1
                docker build . -f Dockerfile.test -t reversing-figlet-test

                docker run --rm -it reversing-figlet-test
                '''
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
